//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.23 at 02:39:01 PM CEST 
//

package com.epam.training.sportsbetting.web.models;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "userName", "name", "accountNumber", "balance", "currency", "dateOfBirth", "sportEvents" })
@XmlRootElement(name = "playerInfo")
public class PlayerInfoModel {

	@XmlElement(required = true)
    protected String userName;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String accountNumber;
    protected float balance;
    @XmlElement(required = true)
    protected String currency;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected String dateOfBirth;
    @XmlElement(required = true)
    protected PlayerInfoModel.SportEvents sportEvents;

    public String getUserName() {
        return userName;
    }

    public void setUserName(String value) {
        this.userName = value;
    }
    
    public String getName() {
        return name;
    }

    public void setName(String value) {
        this.name = value;
    }

    public String getAccountNumber() {
        return accountNumber;
    }

    public void setAccountNumber(String value) {
        this.accountNumber = value;
    }

    public float getBalance() {
        return balance;
    }

    public void setBalance(float value) {
        this.balance = value;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String value) {
        this.currency = value;
    }

    public String getDateOfBirth() {
        return dateOfBirth;
    }

    public void setDateOfBirth(String value) {
        this.dateOfBirth = value;
    }

    public PlayerInfoModel.SportEvents getSportEvents() {
        return sportEvents;
    }

    public void setSportEvents(PlayerInfoModel.SportEvents value) {
        this.sportEvents = value;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "sportEvent" })
    public static class SportEvents {

        @XmlElement(required = true)
        protected PlayerInfoModel.SportEvents.SportEvent sportEvent;

        public PlayerInfoModel.SportEvents.SportEvent getSportEvent() {
            return sportEvent;
        }

        public void setSportEvent(PlayerInfoModel.SportEvents.SportEvent value) {
            this.sportEvent = value;
        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = { "wagers" })
        public static class SportEvent {

            @XmlElement(required = true)
            protected PlayerInfoModel.SportEvents.SportEvent.Wagers wagers;

            public PlayerInfoModel.SportEvents.SportEvent.Wagers getWagers() {
                return wagers;
            }

            public void setWagers(PlayerInfoModel.SportEvents.SportEvent.Wagers value) {
                this.wagers = value;
            }

            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = { "wager" })
            public static class Wagers {

                @XmlElement(required = true)
                protected List<PlayerInfoModel.SportEvents.SportEvent.Wagers.Wager> wager;

                public List<PlayerInfoModel.SportEvents.SportEvent.Wagers.Wager> getWager() {
                    if (wager == null) {
                        wager = new ArrayList<PlayerInfoModel.SportEvents.SportEvent.Wagers.Wager>();
                    }
                    return this.wager;
                }

                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = { "betType", "betDescription", "outcomeValue", "amount", "currency", "odd", "win", "date" })
                public static class Wager {

                    @XmlElement(required = true)
                    protected String betType;
                    @XmlElement(required = true)
                    protected String betDescription;
                    @XmlElement(required = true)
                    protected String outcomeValue;
                    @XmlElement(required = true)
                    protected BigInteger amount;
                    @XmlElement(required = true)
                    protected String currency;
                    protected float odd;
                    @XmlElement(required = true)
                    protected boolean win;
                    @XmlElement(required = true)
                    @XmlSchemaType(name = "dateTime")
                    protected String date;

                    public String getBetType() {
                        return betType;
                    }

                    public void setBetType(String value) {
                        this.betType = value;
                    }

                    public String getBetDescription() {
                        return betDescription;
                    }

                    public void setBetDescription(String value) {
                        this.betDescription = value;
                    }

                    public String getOutcomeValue() {
                        return outcomeValue;
                    }

                    public void setOutcomeValue(String value) {
                        this.outcomeValue = value;
                    }

                    public BigInteger getAmount() {
                        return amount;
                    }

                    public void setAmount(BigInteger value) {
                        this.amount = value;
                    }

                    public String getCurrency() {
                        return currency;
                    }

                    public void setCurrency(String value) {
                        this.currency = value;
                    }

                    public float getOdd() {
                        return odd;
                    }

                    public void setOdd(float value) {
                        this.odd = value;
                    }

                    public boolean getWin() {
                        return win;
                    }

                    public void setWin(boolean value) {
                        this.win = value;
                    }

                    public String getDate() {
                        return date;
                    }

                    public void setDate(String value) {
                        this.date = value;
                    }

                }
            }
        }
    }
}
